### ISSUE TITLE
ADD STICKETS PLEASE

### ISSUE THREAD

**Issue by facundolinlaud** [btuso/chequeado#1]
DEAR BERNIARDO

PLEASE ADD STICKERS INSTEAD OF IMAGES

YOU ARE HURTING MOTHER EARTH

THANK YOU

**Comment by ivanpondal** [comment]
This feature has been on hold for years... The coronavirus pandemic put us together in the digital medium for us to realize, our beloved bot still uses images. We are not over this, together we stand: BRING OUR STICKERS HOME

**Comment by btuso** [comment]
This is now pending QA/QC and code review

**Comment by facundolinlaud** [comment]
> This feature has been on hold for years... The coronavirus pandemic put us together in the digital medium for us to realize, our beloved bot still uses images. We are not over this, together we stand: BRING OUR STICKERS HOME

Your words warmed my heart @ivanpondal.

Our mission is to make the world a better place for everybody, and [ADD STICKER SUPPORT #2](https://github.com/btuso/chequeado/issues/1) will definitely contribute to this goal.

Thank you @btuso for your effort. Let's get this feature shipped!! #chequeadofamily #withchequeadowearebetter #impuestoalcheque

**Comment by btuso** [comment]
My friends, all is good in the world. Stickers are now supported and encouraged.

**Comment by ivanpondal** [comment]
I CAN NOW REST IN PEACE :sparkle:
